export const COUNTRY_OPTIONS = [
  'Argentina',
  'Australia',
  'Austria',
  'Bélgica',
  'Bolivia',
  'Brasil',
  'Canadá',
  'Chile',
  'China',
  'Colombia',
  'Costa Rica',
  'Cuba',
  'Dinamarca',
  'Ecuador',
  'El Salvador',
  'España',
  'Estados Unidos',
  'Finlandia',
  'Francia',
  'Alemania',
  'Grecia',
  'Guatemala',
  'Honduras',
  'India',
  'Indonesia',
  'Irlanda',
  'Italia',
  'Japón',
  'México',
  'Nicaragua',
  'Noruega',
  'Países Bajos',
  'Panamá',
  'Paraguay',
  'Perú',
  'Portugal',
  'Puerto Rico',
  'Reino Unido',
  'República Dominicana',
  'Suecia',
  'Suiza',
  'Uruguay',
  'Venezuela',
  'Nueva Zelanda',
  'Corea del Sur',
  'Filipinas',
  'Sudáfrica',
].sort((a, b) => a.localeCompare(b, 'es'));